# Generated by Django 4.1 on 2022-09-14 16:47

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('role', models.CharField(choices=[(user.models.UserRoles['USER'], 'Пользователь'), (user.models.UserRoles['ADMIN'], 'Администратор')], max_length=9)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=11)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
